const defaultEmployerQuestions = [
  {
    id: "join-window",
    label: "Can you join within 15 days?",
    type: "radio",
    options: ["Yes", "No"],
    required: true
  },
  {
    id: "similar-role-exp",
    label: "Share your relevant experience for this role.",
    type: "text",
    placeholder: "Mention years, tools handled, and project type.",
    required: true
  }
];

export const mockJobs = [
  {
    id: 1,
    company: "Horizon Marine Services",
    location: "Mumbai",
    title: "Marine Electrician",
    type: "Full time",
    time: "2 hours ago",
    price: "INR 220",
    desc: "Maintenance of onboard panels, cable routing, and electrical safety checks for vessel operations.",
    tags: ["Panel Wiring", "Safety Compliance"],
    workMode: "On-site",
    department: "Maintenance",
    experience: "3-5 Years",
    salaryRange: "INR 45K - INR 60K",
    role: "Marine Electrician",
    industries: ["Marine", "Shipping"],
    postedBy: "Company",
    freshness: "Last 24 hours",
    openings: 6,
    img: "/assets/imgs/brands/brand-1.png",
    employerQuestions: [
      {
        id: "passport",
        label: "Do you have a valid passport with 6+ months validity?",
        type: "radio",
        options: ["Yes", "No"],
        required: true
      },
      {
        id: "panel-exp",
        label: "What type of marine electrical panels have you handled?",
        type: "text",
        placeholder: "Mention panel types and vessel category.",
        required: true
      }
    ]
  },
  {
    id: 2,
    company: "Westbay Infrastructure",
    location: "Pune",
    title: "Site Welder (6G)",
    type: "Contract",
    time: "4 hours ago",
    price: "INR 260",
    desc: "Structural and pipeline welding for industrial site projects with mandatory quality testing.",
    tags: ["6G Welding", "Fabrication"],
    workMode: "On-site",
    department: "Fabrication",
    experience: "5-10 Years",
    salaryRange: "INR 50K - INR 72K",
    role: "Welder",
    industries: ["Construction", "Industrial"],
    postedBy: "Company",
    freshness: "Last 24 hours",
    openings: 8,
    img: "/assets/imgs/brands/brand-2.png",
    employerQuestions: [
      {
        id: "welding-cert",
        label: "Which welding certifications are currently active?",
        type: "text",
        placeholder: "List active certification IDs.",
        required: true
      },
      {
        id: "night-shift",
        label: "Are you comfortable in rotational shifts?",
        type: "radio",
        options: ["Yes", "No"],
        required: true
      }
    ]
  },
  {
    id: 3,
    company: "Metro Cargo Logistics",
    location: "Delhi / NCR",
    title: "Warehouse Supervisor",
    type: "Full time",
    time: "8 hours ago",
    price: "INR 190",
    desc: "Lead dispatch crews, maintain inventory accuracy, and coordinate loading schedules across shifts.",
    tags: ["Dispatch Planning", "Inventory"],
    workMode: "On-site",
    department: "Operations",
    experience: "3-5 Years",
    salaryRange: "INR 38K - INR 52K",
    role: "Warehouse Supervisor",
    industries: ["Logistics"],
    postedBy: "Recruiter",
    freshness: "Last 24 hours",
    openings: 3,
    img: "/assets/imgs/brands/brand-3.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 4,
    company: "Gulf Hospitality Group",
    location: "Kochi",
    title: "Commis Cook (Bulk Kitchen)",
    type: "Full time",
    time: "1 day ago",
    price: "INR 170",
    desc: "Meal prep for large teams with strict hygiene and food safety standards.",
    tags: ["Food Safety", "Bulk Kitchen"],
    workMode: "On-site",
    department: "Hospitality",
    experience: "1-3 Years",
    salaryRange: "INR 30K - INR 42K",
    role: "Cook",
    industries: ["Hospitality"],
    postedBy: "Company",
    freshness: "Last 3 days",
    openings: 4,
    img: "/assets/imgs/brands/brand-4.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 5,
    company: "Apex Industrial Projects",
    location: "Chennai",
    title: "Mechanical Fitter",
    type: "Full time",
    time: "1 day ago",
    price: "INR 210",
    desc: "Assembly and alignment of rotating equipment for manufacturing and maintenance projects.",
    tags: ["Alignment", "Machine Assembly"],
    workMode: "On-site",
    department: "Maintenance",
    experience: "3-5 Years",
    salaryRange: "INR 40K - INR 56K",
    role: "Fitter",
    industries: ["Manufacturing", "Industrial"],
    postedBy: "Company",
    freshness: "Last 3 days",
    openings: 5,
    img: "/assets/imgs/brands/brand-5.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 6,
    company: "Portline Engineering",
    location: "Visakhapatnam",
    title: "Rigger",
    type: "Contract",
    time: "2 days ago",
    price: "INR 230",
    desc: "Rigging execution for heavy lifts with crane teams and safety officers on active project sites.",
    tags: ["Heavy Lift", "Signal Handling"],
    workMode: "On-site",
    department: "Operations",
    experience: "3-5 Years",
    salaryRange: "INR 44K - INR 58K",
    role: "Rigger",
    industries: ["Marine", "Construction"],
    postedBy: "Consultant",
    freshness: "Last 3 days",
    openings: 7,
    img: "/assets/imgs/brands/brand-6.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 7,
    company: "Prime Facility Works",
    location: "Bengaluru",
    title: "Plumbing Technician",
    type: "Full time",
    time: "2 days ago",
    price: "INR 175",
    desc: "Installation and maintenance of water supply, drainage, and pressure systems in commercial complexes.",
    tags: ["Leak Testing", "Blueprint Reading"],
    workMode: "On-site",
    department: "Maintenance",
    experience: "1-3 Years",
    salaryRange: "INR 30K - INR 45K",
    role: "Plumber",
    industries: ["Construction"],
    postedBy: "Company",
    freshness: "Last 7 days",
    openings: 6,
    img: "/assets/imgs/brands/brand-7.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 8,
    company: "TransCity Fleet",
    location: "Hyderabad",
    title: "Heavy Vehicle Driver",
    type: "Full time",
    time: "3 days ago",
    price: "INR 160",
    desc: "Inter-city fleet movement, trip logs, and vehicle safety checks for scheduled consignments.",
    tags: ["HMV License", "Trip Logs"],
    workMode: "On-site",
    department: "Transport",
    experience: "3-5 Years",
    salaryRange: "INR 28K - INR 40K",
    role: "Driver",
    industries: ["Logistics"],
    postedBy: "Recruiter",
    freshness: "Last 7 days",
    openings: 10,
    img: "/assets/imgs/brands/brand-8.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 9,
    company: "BluePeak Fabricators",
    location: "Noida",
    title: "TIG Welder",
    type: "Full time",
    time: "4 days ago",
    price: "INR 240",
    desc: "Precision TIG welding on stainless components for fabrication and maintenance orders.",
    tags: ["TIG", "Quality Checks"],
    workMode: "On-site",
    department: "Fabrication",
    experience: "3-5 Years",
    salaryRange: "INR 46K - INR 62K",
    role: "Welder",
    industries: ["Manufacturing"],
    postedBy: "Company",
    freshness: "Last 7 days",
    openings: 4,
    img: "/assets/imgs/brands/brand-1.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 10,
    company: "Harbor Crew Services",
    location: "Goa",
    title: "Deck Crew Assistant",
    type: "Contract",
    time: "5 days ago",
    price: "INR 180",
    desc: "Assist operations teams in docking, rope handling, and onboard safety preparation routines.",
    tags: ["Deck Support", "Safety Drill"],
    workMode: "On-site",
    department: "Operations",
    experience: "1-3 Years",
    salaryRange: "INR 32K - INR 45K",
    role: "Deck Crew",
    industries: ["Marine"],
    postedBy: "Company",
    freshness: "Last 7 days",
    openings: 12,
    img: "/assets/imgs/brands/brand-2.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 11,
    company: "Skyline Structures",
    location: "Ahmedabad",
    title: "Shuttering Carpenter",
    type: "Full time",
    time: "6 days ago",
    price: "INR 190",
    desc: "Formwork setup for high-rise project phases with layout reading and on-site coordination.",
    tags: ["Formwork", "Layout Reading"],
    workMode: "On-site",
    department: "Construction",
    experience: "3-5 Years",
    salaryRange: "INR 36K - INR 50K",
    role: "Carpenter",
    industries: ["Construction"],
    postedBy: "Recruiter",
    freshness: "Last 7 days",
    openings: 9,
    img: "/assets/imgs/brands/brand-3.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 12,
    company: "Thermal Utility Systems",
    location: "Nagpur",
    title: "Boiler Operator",
    type: "Full time",
    time: "1 week ago",
    price: "INR 210",
    desc: "Operate and monitor utility boilers, log readings, and support preventive maintenance programs.",
    tags: ["Boiler Ops", "Log Sheets"],
    workMode: "On-site",
    department: "Utilities",
    experience: "5-10 Years",
    salaryRange: "INR 42K - INR 58K",
    role: "Boiler Operator",
    industries: ["Industrial"],
    postedBy: "Company",
    freshness: "Last 30 days",
    openings: 2,
    img: "/assets/imgs/brands/brand-4.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 13,
    company: "Metroline Services",
    location: "Lucknow",
    title: "HVAC Technician",
    type: "Full time",
    time: "1 week ago",
    price: "INR 200",
    desc: "Install and service HVAC systems for commercial maintenance contracts and new projects.",
    tags: ["HVAC", "Troubleshooting"],
    workMode: "On-site",
    department: "Maintenance",
    experience: "3-5 Years",
    salaryRange: "INR 38K - INR 52K",
    role: "HVAC Technician",
    industries: ["Facility", "Construction"],
    postedBy: "Company",
    freshness: "Last 30 days",
    openings: 5,
    img: "/assets/imgs/brands/brand-5.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 14,
    company: "Summit Industrial Coatings",
    location: "Jamnagar",
    title: "Sand Blasting Operator",
    type: "Contract",
    time: "8 days ago",
    price: "INR 215",
    desc: "Surface preparation and coating support for heavy industrial structures and vessels.",
    tags: ["Blasting", "Coating Prep"],
    workMode: "On-site",
    department: "Surface Treatment",
    experience: "1-3 Years",
    salaryRange: "INR 34K - INR 48K",
    role: "Blasting Operator",
    industries: ["Industrial", "Marine"],
    postedBy: "Consultant",
    freshness: "Last 30 days",
    openings: 8,
    img: "/assets/imgs/brands/brand-6.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 15,
    company: "CargoLine Ports",
    location: "Kandla",
    title: "Forklift Operator",
    type: "Full time",
    time: "10 days ago",
    price: "INR 165",
    desc: "Container movement, loading support, and material handling in high-volume yard operations.",
    tags: ["Forklift", "Material Handling"],
    workMode: "On-site",
    department: "Logistics",
    experience: "1-3 Years",
    salaryRange: "INR 28K - INR 38K",
    role: "Forklift Operator",
    industries: ["Logistics", "Marine"],
    postedBy: "Company",
    freshness: "Last 30 days",
    openings: 11,
    img: "/assets/imgs/brands/brand-7.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 16,
    company: "BuildCore Projects",
    location: "Jaipur",
    title: "Civil Site Foreman",
    type: "Full time",
    time: "12 days ago",
    price: "INR 260",
    desc: "Coordinate civil crews, daily progress logs, and QA checks for active infrastructure projects.",
    tags: ["Site Coordination", "QA"],
    workMode: "On-site",
    department: "Construction",
    experience: "5-10 Years",
    salaryRange: "INR 52K - INR 70K",
    role: "Foreman",
    industries: ["Construction"],
    postedBy: "Recruiter",
    freshness: "Last 30 days",
    openings: 3,
    img: "/assets/imgs/brands/brand-8.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 17,
    company: "Portline Engineering",
    location: "Kolkata",
    title: "Pipe Fitter",
    type: "Contract",
    time: "14 days ago",
    price: "INR 225",
    desc: "Pipe routing, alignment, and leak testing for maintenance and turnaround projects.",
    tags: ["Pipe Fit-up", "Hydro Test"],
    workMode: "On-site",
    department: "Fabrication",
    experience: "3-5 Years",
    salaryRange: "INR 44K - INR 60K",
    role: "Pipe Fitter",
    industries: ["Industrial", "Marine"],
    postedBy: "Company",
    freshness: "Last 30 days",
    openings: 7,
    img: "/assets/imgs/brands/brand-1.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 18,
    company: "SafeGuard Fire Systems",
    location: "Indore",
    title: "Fire Safety Technician",
    type: "Full time",
    time: "18 days ago",
    price: "INR 180",
    desc: "Fire system installation, panel checks, and compliance reporting for industrial facilities.",
    tags: ["Fire Panel", "Compliance"],
    workMode: "On-site",
    department: "Safety",
    experience: "1-3 Years",
    salaryRange: "INR 32K - INR 44K",
    role: "Fire Safety Technician",
    industries: ["Industrial", "Facility"],
    postedBy: "Company",
    freshness: "Last 30 days",
    openings: 5,
    img: "/assets/imgs/brands/brand-2.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 19,
    company: "Oceanview Energy",
    location: "Daman",
    title: "Offshore Safety Steward",
    type: "Rotation",
    time: "3 weeks ago",
    price: "INR 300",
    desc: "Safety drills, permit-to-work support, and incident readiness for offshore operations.",
    tags: ["PTW", "Offshore Safety"],
    workMode: "On-site",
    department: "Safety",
    experience: "5-10 Years",
    salaryRange: "INR 65K - INR 90K",
    role: "Safety Steward",
    industries: ["Oil and Gas", "Marine"],
    postedBy: "Consultant",
    freshness: "Last 30 days",
    openings: 2,
    img: "/assets/imgs/brands/brand-3.png",
    employerQuestions: defaultEmployerQuestions
  },
  {
    id: 20,
    company: "CityCare Facility",
    location: "Bhopal",
    title: "General Maintenance Technician",
    type: "Full time",
    time: "1 month ago",
    price: "INR 150",
    desc: "Electrical, plumbing, and preventive checks for residential and commercial maintenance teams.",
    tags: ["Multi-skill", "Preventive Maintenance"],
    workMode: "On-site",
    department: "Maintenance",
    experience: "Fresher (0-1 yr)",
    salaryRange: "INR 22K - INR 30K",
    role: "Maintenance Technician",
    industries: ["Facility"],
    postedBy: "Company",
    freshness: "Last 30 days",
    openings: 6,
    img: "/assets/imgs/brands/brand-4.png",
    employerQuestions: defaultEmployerQuestions
  }
];

export const industries = [
  "Construction",
  "Marine",
  "Manufacturing",
  "Logistics",
  "Hospitality",
  "Oil and Gas",
  "Industrial",
  "Facility"
];

export const locations = [
  "Mumbai",
  "Pune",
  "Delhi / NCR",
  "Chennai",
  "Hyderabad",
  "Bengaluru",
  "Kochi",
  "Noida",
  "Ahmedabad",
  "Kolkata"
];

