export const mockJobs = [
  {
    id: 1,
    company: 'LinkedIn',
    location: 'Pune',
    title: 'UI / UX Designer fulltime',
    type: 'Fulltime',
    time: '4 mins ago',
    price: '$500',
    desc: 'Verified profile details and role requirements are shown clearly so applicants can assess fit before applying.',
    tags: ['Adobe XD', 'Figma'],
    workMode: 'Hybrid',
    department: 'Design',
    experience: '3–5 Years',
    salaryRange: '₹10 – ₹20 LPA',
    role: 'Full Stack Dev',
    industries: ['IT & Software'],
    postedBy: 'Company',
    freshness: 'Last 7 days',
    img: '/assets/imgs/brands/brand-1.png'
  },
  {
    id: 2,
    company: 'Adobe Illustrator',
    location: 'Bengaluru',
    title: 'Full Stack Engineer',
    type: 'Part time',
    time: '5 mins ago',
    price: '$800',
    desc: 'Verified profile details and role requirements are shown clearly so applicants can assess fit before applying.',
    tags: ['Adobe XD', 'Figma'],
    workMode: 'Remote',
    department: 'Engineering',
    experience: '5–10 Years',
    salaryRange: '₹20+ LPA',
    role: 'Full Stack Dev',
    industries: ['IT & Software'],
    postedBy: 'Recruiter',
    freshness: 'Last 24 hours',
    img: '/assets/imgs/brands/brand-2.png'
  },
  {
    id: 3,
    company: 'Bing Search',
    location: 'Hyderabad',
    title: 'Java Software Engineer',
    type: 'Full time',
    time: '6 mins ago',
    price: '$250',
    desc: 'Verified profile details and role requirements are shown clearly so applicants can assess fit before applying.',
    tags: ['Adobe XD', 'Figma'],
    workMode: 'On-site',
    department: 'Engineering',
    experience: '1–3 Years',
    salaryRange: '₹6 – ₹10 LPA',
    role: 'Backend Dev',
    industries: ['IT & Software'],
    postedBy: 'Company',
    freshness: 'Last 3 days',
    img: '/assets/imgs/brands/brand-3.png'
  },
  {
    id: 4,
    company: 'Dailymotion',
    location: 'Mumbai',
    title: 'Frontend Developer',
    type: 'Full time',
    time: '6 mins ago',
    price: '$250',
    tags: ['Adobe XD', 'Figma'],
    workMode: 'Remote',
    department: 'Engineering',
    experience: 'Fresher (0–1 yr)',
    salaryRange: '₹3 – ₹6 LPA',
    role: 'Frontend Dev',
    industries: ['IT & Software'],
    postedBy: 'Company',
    freshness: 'Last 24 hours',
    img: '/assets/imgs/brands/brand-4.png'
  },
  {
    id: 5,
    company: 'LinkedIn',
    location: 'Chennai',
    title: 'React Native Web Developer',
    type: 'Fulltime',
    time: '4 mins ago',
    price: '$500',
    tags: ['Figma', 'Adobe XD'],
    workMode: 'Hybrid',
    department: 'Engineering',
    experience: '3–5 Years',
    salaryRange: '₹6 – ₹10 LPA',
    role: 'Full Stack Dev',
    industries: ['IT & Software'],
    postedBy: 'Recruiter',
    freshness: 'Last 7 days',
    img: '/assets/imgs/brands/brand-5.png'
  },
  {
    id: 6,
    company: 'Quora JSC',
    location: 'Delhi / NCR',
    title: 'Senior System Engineer',
    type: 'Part time',
    time: '5 mins ago',
    price: '$800',
    desc: 'Verified profile details and role requirements are shown clearly so applicants can assess fit before applying.',
    tags: ['Adobe XD', 'Figma'],
    workMode: 'On-site',
    department: 'Engineering',
    experience: '10+ Years',
    salaryRange: '₹20+ LPA',
    role: 'DevOps',
    industries: ['IT & Software'],
    postedBy: 'Consultant',
    freshness: 'Last 30 days',
    img: '/assets/imgs/brands/brand-6.png'
  },
  {
    id: 7,
    company: 'Nintendo',
    location: 'Pune',
    title: 'Products Manager',
    type: 'Full time',
    time: '6 mins ago',
    price: '$250',
    desc: 'Verified profile details and role requirements are shown clearly so applicants can assess fit before applying.',
    tags: ['Adobe XD', 'Figma'],
    workMode: 'Hybrid',
    department: 'Marketing',
    experience: '5–10 Years',
    salaryRange: '₹10 – ₹20 LPA',
    role: 'Full Stack Dev',
    industries: ['E-commerce'],
    postedBy: 'Company',
    freshness: 'Last 3 days',
    img: '/assets/imgs/brands/brand-7.png'
  },
  {
    id: 8,
    company: 'Periscope',
    location: 'Bengaluru',
    title: 'Lead Quality Control QA',
    type: 'Full time',
    time: '6 mins ago',
    price: '$250',
    desc: 'Verified profile details and role requirements are shown clearly so applicants can assess fit before applying.',
    tags: ['Adobe XD', 'Figma'],
    workMode: 'On-site',
    department: 'Engineering',
    experience: '3–5 Years',
    salaryRange: '₹6 – ₹10 LPA',
    role: 'DevOps',
    industries: ['IT & Software'],
    postedBy: 'Recruiter',
    freshness: 'Last 7 days',
    img: '/assets/imgs/brands/brand-8.png'
  },
  {
    id: 9,
    company: 'Google',
    location: 'London, UK',
    title: 'Backend Developer',
    type: 'Fulltime',
    time: '2 mins ago',
    price: '$600',
    desc: 'Advanced backend role with Node.js and databases.',
    tags: ['Node.js', 'MongoDB'],
    workMode: 'Remote',
    department: 'Engineering',
    experience: '5–10 Years',
    salaryRange: '₹20+ LPA',
    role: 'Backend Dev',
    industries: ['IT & Software'],
    postedBy: 'Company',
    freshness: 'Last 24 hours',
    img: '/assets/imgs/brands/brand-1.png'
  },
  {
    id: 10,
    company: 'Microsoft',
    location: 'Paris, FR',
    title: 'DevOps Engineer',
    type: 'Part time',
    time: '1 hour ago',
    price: '$400',
    desc: 'DevOps position focusing on CI/CD pipelines.',
    tags: ['Docker', 'Kubernetes'],
    workMode: 'Hybrid',
    department: 'Engineering',
    experience: '3–5 Years',
    salaryRange: '₹10 – ₹20 LPA',
    role: 'DevOps',
    industries: ['IT & Software'],
    postedBy: 'Recruiter',
    freshness: 'Last 3 days',
    img: '/assets/imgs/brands/brand-2.png'
  },
  {
    id: 11,
    company: 'Amazon',
    location: 'Berlin, DE',
    title: 'Data Scientist',
    type: 'Full time',
    time: '3 hours ago',
    price: '$900',
    desc: 'Data analysis and ML model deployment.',
    tags: ['Python', 'TensorFlow'],
    workMode: 'Remote',
    department: 'Engineering',
    experience: '5–10 Years',
    salaryRange: '₹20+ LPA',
    role: 'Data Engineer',
    industries: ['IT & Software'],
    postedBy: 'Company',
    freshness: 'Last 7 days',
    img: '/assets/imgs/brands/brand-3.png'
  },
  {
    id: 12,
    company: 'Facebook',
    location: 'Mumbai',
    title: 'Product Designer',
    type: 'Fulltime',
    time: '1 day ago',
    price: '$550',
    desc: 'Design user interfaces for social platform.',
    tags: ['Sketch', 'Figma'],
    workMode: 'On-site',
    department: 'Design',
    experience: '1–3 Years',
    salaryRange: '₹6 – ₹10 LPA',
    role: 'Frontend Dev',
    industries: ['IT & Software'],
    postedBy: 'Company',
    freshness: 'Last 30 days',
    img: '/assets/imgs/brands/brand-4.png'
  },
  {
    id: 13,
    company: 'Apple',
    location: 'Chennai',
    title: 'iOS Developer',
    type: 'Full time',
    time: '2 days ago',
    price: '$700',
    desc: 'Develop native iOS applications.',
    tags: ['Swift', 'Xcode'],
    workMode: 'Hybrid',
    department: 'Engineering',
    experience: 'Fresher (0–1 yr)',
    salaryRange: '₹3 – ₹6 LPA',
    role: 'Full Stack Dev',
    industries: ['IT & Software'],
    postedBy: 'Recruiter',
    freshness: 'Last 7 days',
    img: '/assets/imgs/brands/brand-5.png'
  },
  {
    id: 14,
    company: 'Netflix',
    location: 'Delhi / NCR',
    title: 'Full Stack Developer',
    type: 'Part time',
    time: '5 days ago',
    price: '$450',
    desc: 'Build scalable web applications.',
    tags: ['React', 'Node'],
    workMode: 'Remote',
    department: 'Engineering',
    experience: '10+ Years',
    salaryRange: '₹20+ LPA',
    role: 'Full Stack Dev',
    industries: ['IT & Software'],
    postedBy: 'Company',
    freshness: 'Last 30 days',
    img: '/assets/imgs/brands/brand-6.png'
  },
  {
    id: 15,
    company: 'Tesla',
    location: 'Pune',
    title: 'Embedded Software Engineer',
    type: 'Full time',
    time: '1 week ago',
    price: '$850',
    desc: 'Firmware development for automotive systems.',
    tags: ['C++', 'Embedded'],
    workMode: 'On-site',
    department: 'Engineering',
    experience: '5–10 Years',
    salaryRange: '₹10 – ₹20 LPA',
    role: 'Backend Dev',
    industries: ['IT & Software'],
    postedBy: 'Consultant',
    freshness: 'Last 30 days',
    img: '/assets/imgs/brands/brand-7.png'
  },
  {
    id: 16,
    company: 'SpaceX',
    location: 'Bengaluru',
    title: 'Aerospace Engineer',
    type: 'Fulltime',
    time: '2 weeks ago',
    price: '$950',
    desc: 'Rocket propulsion systems engineering.',
    tags: ['CAD', 'Simulation'],
    workMode: 'Hybrid',
    department: 'Engineering',
    experience: '10+ Years',
    salaryRange: '₹20+ LPA',
    role: 'Data Engineer',
    industries: ['IT & Software'],
    postedBy: 'Company',
    freshness: 'Last 30 days',
    img: '/assets/imgs/brands/brand-8.png'
  },
  {
    id: 17,
    company: 'Uber',
    location: 'Hyderabad',
    title: 'Mobile Developer',
    type: 'Part time',
    time: '3 weeks ago',
    price: '$350',
    desc: 'Android/iOS app development.',
    tags: ['Kotlin', 'Swift'],
    workMode: 'Remote',
    department: 'Engineering',
    experience: '1–3 Years',
    salaryRange: '₹3 – ₹6 LPA',
    role: 'Frontend Dev',
    industries: ['IT & Software'],
    postedBy: 'Recruiter',
    freshness: 'Last 30 days',
    img: '/assets/imgs/brands/brand-1.png'
  },
  {
    id: 18,
    company: 'Airbnb',
    location: 'Mumbai',
    title: 'UX Researcher',
    type: 'Full time',
    time: '1 month ago',
    price: '$420',
    desc: 'User experience research and testing.',
    tags: ['User Testing', 'Analytics'],
    workMode: 'On-site',
    department: 'Design',
    experience: 'Fresher (0–1 yr)',
    salaryRange: '₹0 – ₹3 LPA',
    role: 'Frontend Dev',
    industries: ['E-commerce'],
    postedBy: 'Company',
    freshness: 'Last 30 days',
    img: '/assets/imgs/brands/brand-2.png'
  },
  {
    id: 19,
    company: 'Spotify',
    location: 'Chennai',
    title: 'Backend Engineer',
    type: 'Fulltime',
    time: '2 months ago',
    price: '$650',
    desc: 'Scalable audio streaming backend.',
    tags: ['Java', 'Kafka'],
    workMode: 'Hybrid',
    department: 'Engineering',
    experience: '5–10 Years',
    salaryRange: '₹10 – ₹20 LPA',
    role: 'Backend Dev',
    industries: ['IT & Software'],
    postedBy: 'Company',
    freshness: 'Last 30 days',
    img: '/assets/imgs/brands/brand-3.png'
  },
  {
    id: 20,
    company: 'Dropbox',
    location: 'Delhi / NCR',
    title: 'Security Engineer',
    type: 'Full time',
    time: '3 months ago',
    price: '$750',
    desc: 'Cybersecurity and encryption specialist.',
    tags: ['Security', 'Encryption'],
    workMode: 'On-site',
    department: 'Engineering',
    experience: '3–5 Years',
    salaryRange: '₹6 – ₹10 LPA',
    role: 'DevOps',
    industries: ['IT & Software'],
    postedBy: 'Recruiter',
    freshness: 'Last 30 days',
    img: '/assets/imgs/brands/brand-4.png'
  }
];

export const industries = ['Software', 'Finance', 'Recruiting', 'Management', 'Advertising', 'Development'];
export const locations = ['Pune', 'Bengaluru', 'Hyderabad', 'Mumbai', 'Chennai', 'Delhi / NCR', 'London, UK', 'Paris, FR', 'Berlin, DE'];
