export const filterCategories = [
  { label: 'Work mode', type: 'workMode' },
  { label: 'Department', type: 'department' },
  { label: 'Experience', type: 'experience' },
  { label: 'Salary', type: 'salary' },
  { label: 'Companies', type: 'companies' },
  { label: 'Industries', type: 'industries' },
  { label: 'Role', type: 'role' },
  { label: 'Education', type: 'education' },
  { label: 'Posted by', type: 'postedBy' },
  { label: 'Freshness', type: 'freshness' },
  { label: 'Sort', type: 'sort' },
  { label: 'Location', type: 'location' },
];

export const filterOptions = {
  workMode: [
    { label: 'Remote', count: 312, selected: false },
    { label: 'On-site', count: 1540, selected: false },
    { label: 'Hybrid', count: 874, selected: false },
  ],
  department: [
    { label: 'Engineering', count: 450, selected: false },
    { label: 'Design', count: 180, selected: false },
    { label: 'Marketing', count: 230, selected: false },
    { label: 'Finance', count: 120, selected: false },
    { label: 'HR', count: 95, selected: false },
  ],
  experience: [
    { label: 'Fresher (0–1 yr)', count: 320, selected: false },
    { label: '1–3 Years', count: 780, selected: false },
    { label: '3–5 Years', count: 640, selected: false },
    { label: '5–10 Years', count: 410, selected: false },
    { label: '10+ Years', count: 180, selected: false },
  ],
  salary: [
    { label: '₹0 – ₹3 LPA', count: 56, selected: false },
    { label: '₹3 – ₹6 LPA', count: 375, selected: false },
    { label: '₹6 – ₹10 LPA', count: 482, selected: false },
    { label: '₹10 – ₹20 LPA', count: 310, selected: false },
    { label: '₹20+ LPA', count: 98, selected: false },
  ],
  companies: [
    { label: 'TCS', count: 145, selected: false },
    { label: 'Infosys', count: 132, selected: false },
    { label: 'Wipro', count: 98, selected: false },
    { label: 'Accenture', count: 210, selected: false },
    { label: 'Cognizant', count: 176, selected: false },
  ],
  industries: [
    { label: 'IT & Software', count: 920, selected: false },
    { label: 'Banking / Finance', count: 340, selected: false },
    { label: 'Healthcare', count: 210, selected: false },
    { label: 'E-commerce', count: 180, selected: false },
    { label: 'Education', count: 130, selected: false },
  ],
  role: [
    { label: 'Full Stack Dev', count: 285, selected: false },
    { label: 'Backend Dev', count: 312, selected: false },
    { label: 'Frontend Dev', count: 210, selected: false },
    { label: 'Data Engineer', count: 175, selected: false },
    { label: 'DevOps', count: 140, selected: false },
  ],
  education: [
    { label: 'Any Graduate', count: 1200, selected: false },
    { label: 'B.Tech / B.E.', count: 880, selected: false },
    { label: 'MBA', count: 420, selected: false },
    { label: 'MCA', count: 310, selected: false },
    { label: 'BSc IT', count: 240, selected: false },
  ],
  postedBy: [
    { label: 'Company', count: 1800, selected: false },
    { label: 'Recruiter', count: 560, selected: false },
    { label: 'Consultant', count: 340, selected: false },
  ],
  freshness: [
    { label: 'Last 24 hours', count: 145, selected: false },
    { label: 'Last 3 days', count: 380, selected: false },
    { label: 'Last 7 days', count: 720, selected: false },
    { label: 'Last 30 days', count: 1400, selected: false },
  ],
  sort: [
    { label: 'Relevance', count: null, selected: true },
    { label: 'Date (Newest)', count: null, selected: false },
    { label: 'Salary (High–Low)', count: null, selected: false },
    { label: 'Salary (Low–High)', count: null, selected: false },
  ],
  location: [
    { label: 'Pune', count: 2061, selected: false },
    { label: 'Bengaluru', count: 439, selected: false },
    { label: 'Hyderabad', count: 373, selected: false },
    { label: 'Mumbai (All Areas)', count: 367, selected: false },
    { label: 'Mumbai', count: 353, selected: false },
    { label: 'Chennai', count: 332, selected: false },
    { label: 'Delhi / NCR', count: 331, selected: false },
    { label: 'Kolkata', count: 285, selected: false },
    { label: 'New Delhi', count: 259, selected: false },
    { label: 'Nashik', count: 38, selected: false },
    { label: 'Nagpur', count: 34, selected: false },
    { label: 'Gurugram', count: 31, selected: false },
    { label: 'Aurangabad', count: 30, selected: false },
    { label: 'Thane', count: 29, selected: false },
    { label: 'Noida', count: 28, selected: false },
  ],
};
